DESENHE UM MER  PARA O SEGUINTE CENÁRIO:
UMA ESCOLA DESEJA ARMEZENAR INFORMAÇOES SOBRE SEUS PROFESSORES, E AS DISCIPLINAS
QUE ELES LECIONAM.
UM PROFESSOR PODE DAR VARIAS DISCIPLINAS, E UMA DISCIPLINA PODE SER DADAPOR VARIOS PROFESSORES.
- INDENTIFIQUE AS ENTIDADES, ATRIBUTOS E RELACIONAMENTOS
-DETERMINE A CARDINALIDADE ENTRE AS ENTIDADES.


ENTIDADES  : professor E disciplina ou professor_disciplina

ATRIBUTOS:  id_professor, nome,sobrenome, email, formaçao
            id_disciplina, nome, disciplina, carga_horaria, tipo(anul, semestral)
CARDINALIDADE :N:N

RELACIONAMENTOS: UM POFESSOR PODE LECIONAR VARIAS DISCIPLINAS;
VARIAS DISCILPINAS PODE SER LECIONADO POR VARIOS PROFRESSORES;
 disciplina de matematica, portugues, historia, etc
 
